import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    template: "Taxi City Poreć | %s",
    default: "Taxi City Poreć  | Vaš pouzdani prjevoznik - 0/24",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  antialiased max-w-full text-textColor bg-bgColor`}
      >
        <Navigation />
        <main className="max-w-full container">{children}</main>
        <Footer phone="991985871" />
      </body>
    </html>
  );
}
